
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test with docker
        uses: k6io/action@v0.1
        with:
            filename : k6_scriptt.js
