name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: K6_lama
        default: v1.0.0
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test with docker
        uses: k6io/action@v0.1
        with:
            filename : k6_scriptt.js
