on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to [dev|qa|prod].'
        default: dev
        required: true
      git_reference:
        description: 'Which Git reference to check out. Examples: "refs/tags/v0.2.1", "refs/heads/website/feature_branch" "refs/heads/master".'
        default: refs/tags/vX.Y.Z
        required: true
  push:
    paths:
      - 'my-project-subdirectory/**'
    branches:
      - master

jobs:
  deploy:
    name: Deploy my project

    runs-on:
      - ubuntu-20.04

    steps:
      - name: Set variables
        env:
          DEFAULT_ENVIRONMENT: dev
          DEFAULT_GIT_REFERENCE: refs/heads/master
        run: |
          echo "GIT_REFERENCE=${{ github.event.inputs.git_reference || env.DEFAULT_GIT_REFERENCE }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment || env.DEFAULT_ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Checkout repository at ${{ env.GIT_REFERENCE }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_REFERENCE }}
          fetch-depth: 0

      - name: Build and deploy to ${{ env.ENVIRONMENT }}


