name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      testscript:
        description: 'Script yang ditest'
        default: v1.0.0, 
        required: true
      scriptname:
        description: 'Nama Script'     
        required: true
        default: '**.js'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Test Script: ${{ github.event.inputs.testscript }}"
        echo "Script Name: ${{ github.event.inputs.scriptname }}"

  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test with docker

        uses: k6io/action@v0.1
        with:
            filename : ${{ github.event.inputs.scriptname }}"
